

export const LOAD_PLAYLISTS = 'LOAD_PLAYLISTS'

export const GET_PLAYLISTS_DATA_RECEIVED = 'GET_PLAYLISTS_DATA_RECEIVED'

export const GET_PLAYLIST_SONGS_DATA_RECEIVED = 'GET_PLAYLIST_SONGS_DATA_RECEIVED'

export const GET_SEARCH_DATA_RECEIVED = 'GET_SEARCH_DATA_RECEIVED'

export const SET_PLAYLIST_ID = 'SET_PLAYLIST_ID'





